  - name: Installer le paquet httpd
    yum:
     name: httpd
     state: latest
     disable_gpg_check: no
     update_cache: yes

  - name: replace httpd config value
    template:
      backup: yes
      src: "templates/httpd.conf.j2"
      dest: "/etc/httpd/httpd.conf"
      validate: 'sudo /usr/sbin/apachectl configtest %s'
      group: root
      owner: root
      mode: 0644


