- name: create root path
  file:
    path: "/appl"
    state: directory
    owner: "root"
    group: "root"

- name: Create elasticsearch group
  group:
    name: "{{ es_group }}"
    state: present

- name: Create supervision group
  group:
    name: "{{ nagios_group }}"
    state: present

- name: Create es_user
  user:
    name: "{{ es_user }}"
    group: "{{ es_group }}"
    home: "/appl/{{ es_user }}"

- name: Create supervision user
  user:
    name: "{{ nagios_user }}"
    group: "{{ nagios_group }}"
    home: "/appl/{{ nagios_user }}"

#- name: Install Elasticsearch Curator
#  include: curator-install.yml

- name: Install Cerebro
  include: cerebro-install.yml
